//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceCentral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goals
    {
        public int goalID { get; set; }
        public string name { get; set; }
        public string goalDescription { get; set; }
        public Nullable<decimal> goalTarget { get; set; }
        public Nullable<decimal> goalCurrent { get; set; }
        public Nullable<int> incomeID { get; set; }
    
        public virtual Income Income { get; set; }
    }
}
